module.exports = {
  url: "https://www.davidbergeron.dev",
  pathPrefix: "/",
  title: "David Bergeron | Web Developer",
  description: "David Bergeron's Orange Portfolio",
  copyright: "©2020 David Bergeron All rights reserved.",
  postsPerPage: 4,
  googleAnalyticsId: "UA-165369897-1",
  menu: [
    {
      label: "Articles",
      path: "/",
    },
    {
      label: "About me",
      path: "/pages/about",
    },
    {
      label: "Contact me",
      path: "/pages/contacts",
    },
  ],
  author: {
    name: "David Bergeron",
    photo: "static/photo.jpg",
    bio: "I like building web sites and solving problems.",
    contacts: {
      email: "david.f.bergeron@gmail.com",
      facebook: "",
      telegram: "",
      twitter: "DavidFBergeron",
      github: "SceptreData",
      rss: "",
      vkontakte: "",
      linkedin: "david-bergeron-601290133",
      instagram: "",
      line: "",
      gitlab: "",
      weibo: "",
      codepen: "",
      youtube: "",
      soundcloud: "",
    },
  },
}
